# Generated by Django 5.2 on 2025-05-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="preview_image",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_previews/", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
